orders/urls.py
from django.urls import path
from . import views


app_name = "orders"
urlpatterns = [
    path("view/", views.view_basket, name="basket_view"),
    path("add/<product_id>/", views.add_to_basket, name="basket_add"),
    path("remove/<order_line_id>/", views.remove_from_basket, name="basket_remove"),
    path("empty_basket/<order_id>/", views.empty_basket, name="empty_basket"),
    path("checkout/<order_id>/", views.checkout, name="checkout"),
    path("all_orders/", views.all_orders, name="all_orders"),
]

products/urls.py
from django.urls import path
from . import views

app_name= 'products'
urlpatterns = [
    path('', views.index, name="index"),
    path("products/", views.ProductsViewList.as_view(), name="products_list"),
    path("products/<pk>/", views.ProductDetailView.as_view(), name="product_view")

]

towel_store/urls.py
from django.http import HttpResponse
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('products.urls')),
    path("basket/", include("orders.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from accounts.models import Author


class Category(models.Model):
    name = models.CharField(max_length=128)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    thumbnail = models.ImageField(upload_to="images/")
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, related_name="products")
    price = models.DecimalField(decimal_places=2, max_digits= 10)
    
    PRODUCT_TYPE_CHOICES = (
        ("CTN", "Cotton"),
        ("LNN", "Linen")
    )
    product_type = models.CharField(
        max_length=3,
        choices=PRODUCT_TYPE_CHOICES,
        default="CTN"
    )
    author = models.ForeignKey(to=Author, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.title

products/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product
from orders.forms import CartAddProductForm

def index(request):
    return render(request,'index.html')


# def products(request):
#     my_products = Product.objects.all()
#     return render(request, "products/products_list.html", context={"products": my_products})


class ProductsViewList(ListView):
    template_name = "products/products_list.html"
    model = Product


class ProductDetailView(DetailView):    
    template_name = "products/product_view.html"
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CartAddProductForm
        return context

templates/products/product_view.html
{% extends "base.html" %}
{% load static %}
{% block content %}



<h1>{{ product.title }}</h1>

<img src="{{ product.thumbnail.url }}" alt="Picture of {{ product.title }}" class="pic">

<p>
    {{ product.description|linebreaksbr }}
</p>

<h4>Price: {{ product.price }}€</h4>

<form action="{% url 'orders:basket_add' product.id  %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Add to Cart" class="btn btn-warning">
</form>



{% endblock %}

templates/products/products_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<h1>Our Products:</h1>
    <div class="row">
    {% for product in product_list %}

    
        <div class="col-4">
            <h3>{{ product.title }} ({{ product.category }})</h3>
            <h4>{{ product.price }} €</h4>
            <a href="{% url 'products:product_view' product.pk %}">
                <img src="{{ product.thumbnail.url }}" alt="product" class="pic">
            </a>
            
        </div>

    
        

    {% endfor %}
    </div>


{% endblock %}