accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


app_name = 'accounts'
urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("password_change/", views.MyPasswordChangeView.as_view(), name='password_change'),
    path("sign_up/", views.MySignUpView.as_view(), name='sign_up'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = "orders"
urlpatterns = [
    path("view/", views.view_basket, name="basket_view"),
    path("add/<product_id>/", views.add_to_basket, name="basket_add"),
    path("remove/<order_line_id>/", views.remove_from_basket, name="basket_remove"),
    path("empty_basket/<order_id>/", views.empty_basket, name="empty_basket"),
    path("checkout/<order_id>/", views.checkout, name="checkout"),
    path("all_orders/", views.all_orders, name="all_orders"),
]

products/urls.py
from django.urls import path
from . import views

app_name= 'products'
urlpatterns = [
    path('', views.index, name="index"),
    path("products/", views.ProductsViewList.as_view(), name="products_list"),
    path("products/<pk>/", views.ProductDetailView.as_view(), name="product_view")

]

towel_store/urls.py
from django.http import HttpResponse
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('products.urls')),
    path("basket/", include("orders.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Towel Store</title>
    
    <!--    CSS BootStrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    
    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    
    <!--    JS bootstrap   -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container fixed">
        <a class="navbar-brand" href="/">
          <img src="{% static 'img/rollnlay-01.png' %}" alt="" id="logo-img" class="pic">
        
        </a>
        <button
          class="navbar-toggler" type="button"
          data-toggle="collapse" data-target="#navbarNavAltMarkup"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">           
            <a class="nav-item nav-link active" href="{% url 'products:products_list' %}">
                Products
            </a>
            <a class="nav-item nav-link active" href="{% url 'orders:basket_view' %}">
              Basket
            </a>   
            <a class="nav-item nav-link active" href="{% url 'orders:all_orders' %}">
              Orders History
            </a>    
            <a class="nav-item nav-link active" href="/admin">
              Admin Panel
            </a>
          </div>
        </div>
        <div class="navbar-nav ml-auto">
          <div class="nav-item dropdown">
            {% if user.is_authenticated %}
              <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                {% if user.first_name %}Hello, {{ user.first_name }}!
                {% else %}Hello, {{ user.username }}!{% endif %}
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item text-right" href="{% url 'accounts:logout' %}">Logout</a>
                  <a class="dropdown-item text-right" href="{% url 'accounts:password_change' %}">Change Password</a>
              </div>
            {% else %}
              <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                You are not logged in.
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item text-right" href="{% url 'accounts:login' %}">Login</a>
                <a class="dropdown-item text-right" href="{% url 'accounts:sign_up' %}">Sign Up</a>
              </div>
            {% endif %}
          </div>
          </div>
    </div>
</nav>
<div class="container">
  <div class="jumbotron">
    {% block content %}{% endblock %}
  </div>
</div>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<h1>Our Towels</h1>
  <div class="row">
    <div class="col-6">
      <img src="{% static 'img/intro-1.jpg' %}" alt="Feel the Softness !" class="pic">
    </div>

    <div class="col-6">
      <img src="{% static 'img/intro-2.jpg' %}" alt="Feel the Softness !" class="pic">
    </div>
    
    <div class="col-6">
      <img src="{% static 'img/intro-3.jpg' %}" alt="Feel the Softness !" class="pic">  
    </div>

    <div class="col-6">
      <img src="{% static 'img/intro-4.jpg' %}" alt="Feel the Softness !" class="pic">
    </div>
    
  </div> 

<a href="{% url 'products:products_list' %}">
  <button type="button" class="btn btn-warning middle">See Our Products</button>
</a>

    
{% endblock %}